org.gradle.jvmargs=-Xmx4G --enable-native-access=ALL-UNNAMED -Djava.security.manager=allow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
kotlin.suppressGradlePluginWarnings=true
android.suppressUnsupportedCompileSdk=36
